#!/usr/bin/env bash
# Configure Nginx to include a custom HTTP response header.

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/sites-available/custom-header

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom-header /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

