#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server

# Update package list and install HAProxy
apt-get update
apt-get install -y haproxy

# Define backend server hostnames with IP addresses
web_01="54.87.206.137"
web_02="100.25.199.247"

# Configure HAProxy
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web_01 $web_01:80 check
    server web_02 $web_02:80 check
EOL

# Restart HAProxy service
systemctl restart haproxy

# Output the required hostnames
echo "[$web_01, $web_02]"

