#!/usr/bin/env bash
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
curl -sI http://localhost | grep "HTTP/1.1 200 OK" && echo "Nginx returned a web page with HTTP 200 on port 80." || echo "Error: Nginx did not return the expected response."
service nginx stop
