#!/bin/bash

# Install UFW
sudo apt-get update
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable UFW
sudo ufw enable

# Check UFW status
sudo ufw status

