#!/bin/bash

# Set the passphrase
passphrase="betty"

# Create an RSA key pair with 4096 bits and the specified passphrase
ssh-keygen -t rsa -b 4096 -N "$passphrase" -f ~/.ssh/school

echo "RSA key pair created successfully. Private key: ~/.ssh/school"

